name: PhpUnit Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Composer Install
        uses: php-actions/composer@v1

      - name: PHP Unit Tests
        uses: php-actions/phpunit@v1
