name: PhpUnit Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Composer Install
        uses: php-actions/composer@v1

      - name: Display Composer version
        run: composer --version

      - name: PHP Unit Tests
        run: vendor/bin/phpunit tests
